#GrepIU Config YAML
grepiu:
  file:
    path: "$FILE_PATH$"
  oauth:
    login: "http://localhost:8010"
    token: "http://localhost:8010/oauth/token"
    id: "oauth-client-id"
    secret: "oauth-client-secret"

key:
  google:
    map: "$KEY$"
    geo_url: "https://maps.googleapis.com/maps/api/geocode/json"

management:
  health:
    db:
      enabled: false

server:
  port: 8010

crawler:
  proxy: "10.10.10.10"

spring:
  profiles: local
  aop:
    proxy-target-class: true
  application:
    admin:
      enabled: false
  data:
    mongodb:
      database: grepiu
      host: "localhost"
      port: 27017
      repositories:
       type: auto
    redis:
       host: "192.168.0.76"
       port: 6379
       password: "smartlo20!%"
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

logging:
  level:
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
---

grepiu:
  file:
    path: ""
  oauth:
    login: ""
    token: ""
    id: "oauth-client-id"
    secret: "oauth-client-secret"

key:
  google:
    map: ""
    geo_url: ""

management:
  health:
    db:
      enabled: false

server:
  port: 8080

crawler:
  proxy: "10.10.10.10"

spring:
  profiles: prod
  aop:
    proxy-target-class: true
  application:
    admin:
      enabled: false
  data:
    mongodb:
      database: grepiu
      host: "0.0.0.1"
      username: user
      password: user
      port: 0
      repositories:
       type: auto
    redis:
       host: "0.0.0.0"
       port: 0
       #password: ""
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB
      location: /tmp
logging:
  level:
    org.springframework.web: INFO
  file: ""

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
